on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*-*"

jobs:
  build:
    runs-on: docker
    container:
      image: archlinux:base-devel
    steps:
      - name: Prepare system
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S nodejs git

      - uses: actions/checkout@v4

      - name: Build
        id: build
        run: |
          pacman --noconfirm -S ruby base-devel clang llvm llvm-libs emscripten wget cmake ninja

          source /etc/profile.d/emscripten.sh
          ruby ./build.rb --pack

      - uses: actions/upload-artifact@v3
        with:
          name: browser-llvm-${{ steps.build.outputs.version }}.tar.xz
          path: ./browser-llvm-${{ steps.build.outputs.version }}.tar.xz

      - uses: actions/upload-artifact@v3
        with:
          name: browser-lld-${{ steps.build.outputs.version }}.tar.xz
          path: ./browser-lld-${{ steps.build.outputs.version }}.tar.xz

      - if: startsWith(github.ref, 'refs/tags/')
        uses: actions/action-gh-release@v2
        with:
          files: |
            browser-llvm-${{ steps.build.outputs.version }}.tar.xz
            browser-lld-${{ steps.build.outputs.version }}.tar.xz
